// Code generated by protoc-gen-go.
// source: teletype.proto
// DO NOT EDIT!

/*
Package teletype is a generated protocol buffer package.

It is generated from these files:
	teletype.proto

It has these top-level messages:
	Telecast
*/
package teletype

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TelecastDeviceType int32

const (
	Telecast_UNKNOWN_DEVICE_TYPE TelecastDeviceType = 0
	Telecast_BGEIGIE_NANO        TelecastDeviceType = 1
	Telecast_SIMPLECAST          TelecastDeviceType = 2
	Telecast_TTAPP               TelecastDeviceType = 3
	Telecast_TTRELAY             TelecastDeviceType = 4
	Telecast_TTGATE              TelecastDeviceType = 5
	Telecast_TTSERVE             TelecastDeviceType = 6
)

var TelecastDeviceType_name = map[int32]string{
	0: "UNKNOWN_DEVICE_TYPE",
	1: "BGEIGIE_NANO",
	2: "SIMPLECAST",
	3: "TTAPP",
	4: "TTRELAY",
	5: "TTGATE",
	6: "TTSERVE",
}
var TelecastDeviceType_value = map[string]int32{
	"UNKNOWN_DEVICE_TYPE": 0,
	"BGEIGIE_NANO":        1,
	"SIMPLECAST":          2,
	"TTAPP":               3,
	"TTRELAY":             4,
	"TTGATE":              5,
	"TTSERVE":             6,
}

func (x TelecastDeviceType) Enum() *TelecastDeviceType {
	p := new(TelecastDeviceType)
	*p = x
	return p
}
func (x TelecastDeviceType) String() string {
	return proto.EnumName(TelecastDeviceType_name, int32(x))
}
func (x *TelecastDeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TelecastDeviceType_value, data, "TelecastDeviceType")
	if err != nil {
		return err
	}
	*x = TelecastDeviceType(value)
	return nil
}
func (TelecastDeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type TelecastUnit int32

const (
	Telecast_UNKNOWN_UNIT TelecastUnit = 0
	Telecast_CPM          TelecastUnit = 1
)

var TelecastUnit_name = map[int32]string{
	0: "UNKNOWN_UNIT",
	1: "CPM",
}
var TelecastUnit_value = map[string]int32{
	"UNKNOWN_UNIT": 0,
	"CPM":          1,
}

func (x TelecastUnit) Enum() *TelecastUnit {
	p := new(TelecastUnit)
	*p = x
	return p
}
func (x TelecastUnit) String() string {
	return proto.EnumName(TelecastUnit_name, int32(x))
}
func (x *TelecastUnit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TelecastUnit_value, data, "TelecastUnit")
	if err != nil {
		return err
	}
	*x = TelecastUnit(value)
	return nil
}
func (TelecastUnit) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type Telecast struct {
	DeviceType       *TelecastDeviceType `protobuf:"varint,1,req,name=DeviceType,enum=teletype.TelecastDeviceType" json:"DeviceType,omitempty"`
	DeviceIDString   *string             `protobuf:"bytes,2,opt,name=DeviceIDString" json:"DeviceIDString,omitempty"`
	DeviceIDNumber   *uint32             `protobuf:"varint,3,opt,name=DeviceIDNumber" json:"DeviceIDNumber,omitempty"`
	Message          *string             `protobuf:"bytes,4,opt,name=Message" json:"Message,omitempty"`
	CapturedAt       *string             `protobuf:"bytes,5,opt,name=CapturedAt" json:"CapturedAt,omitempty"`
	Unit             *TelecastUnit       `protobuf:"varint,6,opt,name=Unit,enum=teletype.TelecastUnit" json:"Unit,omitempty"`
	Value            *uint32             `protobuf:"varint,7,opt,name=Value" json:"Value,omitempty"`
	Latitude         *float32            `protobuf:"fixed32,8,opt,name=Latitude" json:"Latitude,omitempty"`
	Longitude        *float32            `protobuf:"fixed32,9,opt,name=Longitude" json:"Longitude,omitempty"`
	Altitude         *uint32             `protobuf:"varint,10,opt,name=Altitude" json:"Altitude,omitempty"`
	BatteryVoltage   *float32            `protobuf:"fixed32,11,opt,name=BatteryVoltage" json:"BatteryVoltage,omitempty"`
	BatterySOC       *float32            `protobuf:"fixed32,12,opt,name=BatterySOC" json:"BatterySOC,omitempty"`
	WirelessSNR      *float32            `protobuf:"fixed32,13,opt,name=WirelessSNR" json:"WirelessSNR,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Telecast) Reset()                    { *m = Telecast{} }
func (m *Telecast) String() string            { return proto.CompactTextString(m) }
func (*Telecast) ProtoMessage()               {}
func (*Telecast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Telecast) GetDeviceType() TelecastDeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Telecast_UNKNOWN_DEVICE_TYPE
}

func (m *Telecast) GetDeviceIDString() string {
	if m != nil && m.DeviceIDString != nil {
		return *m.DeviceIDString
	}
	return ""
}

func (m *Telecast) GetDeviceIDNumber() uint32 {
	if m != nil && m.DeviceIDNumber != nil {
		return *m.DeviceIDNumber
	}
	return 0
}

func (m *Telecast) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Telecast) GetCapturedAt() string {
	if m != nil && m.CapturedAt != nil {
		return *m.CapturedAt
	}
	return ""
}

func (m *Telecast) GetUnit() TelecastUnit {
	if m != nil && m.Unit != nil {
		return *m.Unit
	}
	return Telecast_UNKNOWN_UNIT
}

func (m *Telecast) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Telecast) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Telecast) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Telecast) GetAltitude() uint32 {
	if m != nil && m.Altitude != nil {
		return *m.Altitude
	}
	return 0
}

func (m *Telecast) GetBatteryVoltage() float32 {
	if m != nil && m.BatteryVoltage != nil {
		return *m.BatteryVoltage
	}
	return 0
}

func (m *Telecast) GetBatterySOC() float32 {
	if m != nil && m.BatterySOC != nil {
		return *m.BatterySOC
	}
	return 0
}

func (m *Telecast) GetWirelessSNR() float32 {
	if m != nil && m.WirelessSNR != nil {
		return *m.WirelessSNR
	}
	return 0
}

func init() {
	proto.RegisterType((*Telecast)(nil), "teletype.Telecast")
	proto.RegisterEnum("teletype.TelecastDeviceType", TelecastDeviceType_name, TelecastDeviceType_value)
	proto.RegisterEnum("teletype.TelecastUnit", TelecastUnit_name, TelecastUnit_value)
}

var fileDescriptor0 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xdd, 0xaa, 0xda, 0x40,
	0x10, 0xc7, 0x9b, 0x2f, 0x93, 0x8c, 0xc7, 0x74, 0xbb, 0x07, 0x7a, 0xf6, 0xa6, 0x70, 0x2a, 0x14,
	0xce, 0x95, 0xd0, 0xf3, 0x06, 0x31, 0x2e, 0x12, 0x1a, 0xd7, 0x60, 0xd6, 0x88, 0x57, 0x92, 0xea,
	0x22, 0x81, 0xd4, 0x48, 0xb2, 0x29, 0xf5, 0x61, 0xfb, 0x2e, 0x5d, 0xd7, 0x0f, 0xbc, 0xe8, 0xe5,
	0xfc, 0xe6, 0x3f, 0x33, 0x3f, 0x06, 0x02, 0x29, 0x2a, 0x21, 0x4f, 0x47, 0x31, 0x3a, 0x36, 0xb5,
	0xac, 0xb1, 0x77, 0xab, 0x87, 0x7f, 0x2d, 0xf0, 0xb8, 0x2a, 0xb6, 0x45, 0x2b, 0xf1, 0x77, 0x80,
	0x89, 0xf8, 0x5d, 0x6e, 0x05, 0x57, 0x2d, 0x62, 0xbc, 0x9a, 0x6f, 0xc1, 0xfb, 0x97, 0xd1, 0x7d,
	0xf6, 0x96, 0x1b, 0xed, 0xee, 0x21, 0xfc, 0x19, 0x82, 0xcb, 0x48, 0x3c, 0xc9, 0x64, 0x53, 0x1e,
	0xf6, 0xc4, 0x7c, 0x35, 0xde, 0xfc, 0x47, 0xce, 0xba, 0x5f, 0x3f, 0x45, 0x43, 0x2c, 0xc5, 0x07,
	0xf8, 0x23, 0xb8, 0x33, 0xd1, 0xb6, 0xc5, 0x5e, 0x10, 0x5b, 0x07, 0x31, 0x40, 0x54, 0x1c, 0x65,
	0xd7, 0x88, 0x5d, 0x28, 0x89, 0xa3, 0xd9, 0x37, 0xb0, 0x97, 0x87, 0x52, 0x92, 0x9e, 0xaa, 0x82,
	0xf7, 0x97, 0xff, 0x18, 0x74, 0xaa, 0x8d, 0x07, 0xe0, 0xe4, 0x45, 0xd5, 0x09, 0xe2, 0xea, 0xd5,
	0x08, 0xbc, 0xa4, 0x90, 0xa5, 0xec, 0x76, 0x82, 0x78, 0x8a, 0x98, 0xf8, 0x13, 0xf8, 0x49, 0x7d,
	0xd8, 0x5f, 0x90, 0xaf, 0x91, 0x0a, 0x85, 0xd5, 0x35, 0x04, 0x7a, 0x4c, 0x99, 0x8e, 0x0b, 0x29,
	0x45, 0x73, 0xca, 0xeb, 0x4a, 0x9e, 0xc5, 0xfa, 0x3a, 0xa9, 0xc4, 0xae, 0x3c, 0x9b, 0x47, 0xe4,
	0x49, 0xb3, 0x67, 0xe8, 0xaf, 0xca, 0x46, 0x49, 0xb4, 0x6d, 0xc6, 0x16, 0x64, 0x70, 0x86, 0xc3,
	0x3f, 0x00, 0x0f, 0x0f, 0x79, 0x81, 0xe7, 0x25, 0xfb, 0xc1, 0xe6, 0x2b, 0xb6, 0x99, 0xd0, 0x3c,
	0x8e, 0xe8, 0x86, 0xaf, 0x53, 0x8a, 0x3e, 0xa8, 0xcb, 0x4f, 0xe3, 0x29, 0x8d, 0xa7, 0x31, 0xdd,
	0xb0, 0x90, 0xcd, 0x91, 0x81, 0x03, 0x80, 0x2c, 0x9e, 0xa5, 0x09, 0x8d, 0xc2, 0x8c, 0x23, 0x13,
	0xfb, 0xe0, 0x70, 0x1e, 0xa6, 0x29, 0xb2, 0x70, 0x1f, 0x5c, 0xce, 0x17, 0x34, 0x09, 0xd7, 0xc8,
	0x56, 0x22, 0x3d, 0xce, 0xa7, 0x21, 0xa7, 0xc8, 0xb9, 0x34, 0x32, 0xba, 0xc8, 0x29, 0xea, 0x0d,
	0xbf, 0x82, 0xad, 0x1f, 0xa1, 0x56, 0xdf, 0x6e, 0x2e, 0x59, 0xcc, 0xd5, 0x31, 0x17, 0xac, 0x28,
	0x9d, 0x21, 0xe3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xb4, 0x77, 0xde, 0xfa, 0x01, 0x00,
	0x00,
}
