// Code generated by protoc-gen-go.
// source: tt.proto
// DO NOT EDIT!

/*
Package ttproto is a generated protocol buffer package.

It is generated from these files:
	tt.proto

It has these top-level messages:
	Telecast
*/
package ttproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TelecastDeviceType int32

const (
	Telecast_UNKNOWN_DEVICE_TYPE TelecastDeviceType = 0
	Telecast_BGEIGIE_NANO        TelecastDeviceType = 1
	Telecast_SOLARCAST           TelecastDeviceType = 2
	Telecast_TTAPP               TelecastDeviceType = 3
	Telecast_TTNODE              TelecastDeviceType = 4
	Telecast_TTGATE              TelecastDeviceType = 5
	Telecast_TTSERVE             TelecastDeviceType = 6
)

var TelecastDeviceType_name = map[int32]string{
	0: "UNKNOWN_DEVICE_TYPE",
	1: "BGEIGIE_NANO",
	2: "SOLARCAST",
	3: "TTAPP",
	4: "TTNODE",
	5: "TTGATE",
	6: "TTSERVE",
}
var TelecastDeviceType_value = map[string]int32{
	"UNKNOWN_DEVICE_TYPE": 0,
	"BGEIGIE_NANO":        1,
	"SOLARCAST":           2,
	"TTAPP":               3,
	"TTNODE":              4,
	"TTGATE":              5,
	"TTSERVE":             6,
}

func (x TelecastDeviceType) Enum() *TelecastDeviceType {
	p := new(TelecastDeviceType)
	*p = x
	return p
}
func (x TelecastDeviceType) String() string {
	return proto.EnumName(TelecastDeviceType_name, int32(x))
}
func (x *TelecastDeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TelecastDeviceType_value, data, "TelecastDeviceType")
	if err != nil {
		return err
	}
	*x = TelecastDeviceType(value)
	return nil
}
func (TelecastDeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type TelecastReplyType int32

const (
	Telecast_NO_REPLY      TelecastReplyType = 0
	Telecast_REPLY_ALLOWED TelecastReplyType = 1
)

var TelecastReplyType_name = map[int32]string{
	0: "NO_REPLY",
	1: "REPLY_ALLOWED",
}
var TelecastReplyType_value = map[string]int32{
	"NO_REPLY":      0,
	"REPLY_ALLOWED": 1,
}

func (x TelecastReplyType) Enum() *TelecastReplyType {
	p := new(TelecastReplyType)
	*p = x
	return p
}
func (x TelecastReplyType) String() string {
	return proto.EnumName(TelecastReplyType_name, int32(x))
}
func (x *TelecastReplyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TelecastReplyType_value, data, "TelecastReplyType")
	if err != nil {
		return err
	}
	*x = TelecastReplyType(value)
	return nil
}
func (TelecastReplyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type Telecast struct {
	DeviceType                      *TelecastDeviceType `protobuf:"varint,1,opt,name=device_type,enum=ttproto.TelecastDeviceType" json:"device_type,omitempty"`
	DEPRECATED2017FEBDeviceIDString *string             `protobuf:"bytes,2,opt,name=DEPRECATED2017FEBDeviceIDString" json:"DEPRECATED2017FEBDeviceIDString,omitempty"`
	// This field is actually REQUIRED by ttserve
	DeviceId               *uint32            `protobuf:"varint,3,opt,name=device_id" json:"device_id,omitempty"`
	Message                *string            `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	CapturedAt             *string            `protobuf:"bytes,5,opt,name=captured_at" json:"captured_at,omitempty"`
	ReplyType              *TelecastReplyType `protobuf:"varint,6,opt,name=reply_type,enum=ttproto.TelecastReplyType" json:"reply_type,omitempty"`
	DEPRECATED2017FEBValue *uint32            `protobuf:"varint,7,opt,name=DEPRECATED2017FEBValue" json:"DEPRECATED2017FEBValue,omitempty"`
	Latitude               *float32           `protobuf:"fixed32,8,opt,name=latitude" json:"latitude,omitempty"`
	Longitude              *float32           `protobuf:"fixed32,9,opt,name=longitude" json:"longitude,omitempty"`
	Altitude               *int32             `protobuf:"varint,10,opt,name=altitude" json:"altitude,omitempty"`
	BatVoltage             *float32           `protobuf:"fixed32,11,opt,name=bat_voltage" json:"bat_voltage,omitempty"`
	BatSoc                 *float32           `protobuf:"fixed32,12,opt,name=bat_soc" json:"bat_soc,omitempty"`
	WirelessSnr            *float32           `protobuf:"fixed32,13,opt,name=wireless_snr" json:"wireless_snr,omitempty"`
	EnvTemp                *float32           `protobuf:"fixed32,14,opt,name=env_temp" json:"env_temp,omitempty"`
	EnvHumid               *float32           `protobuf:"fixed32,15,opt,name=env_humid" json:"env_humid,omitempty"`
	RelayDevice1           *uint32            `protobuf:"varint,16,opt,name=relay_device1" json:"relay_device1,omitempty"`
	RelayDevice2           *uint32            `protobuf:"varint,17,opt,name=relay_device2" json:"relay_device2,omitempty"`
	RelayDevice3           *uint32            `protobuf:"varint,18,opt,name=relay_device3" json:"relay_device3,omitempty"`
	RelayDevice4           *uint32            `protobuf:"varint,19,opt,name=relay_device4" json:"relay_device4,omitempty"`
	RelayDevice5           *uint32            `protobuf:"varint,20,opt,name=relay_device5" json:"relay_device5,omitempty"`
	Lnd_7318U              *uint32            `protobuf:"varint,21,opt,name=lnd_7318u" json:"lnd_7318u,omitempty"`
	Lnd_7128Ec             *uint32            `protobuf:"varint,22,opt,name=lnd_7128ec" json:"lnd_7128ec,omitempty"`
	StatsUptimeMinutes     *uint32            `protobuf:"varint,23,opt,name=stats_uptime_minutes" json:"stats_uptime_minutes,omitempty"`
	StatsAppVersion        *string            `protobuf:"bytes,24,opt,name=stats_app_version" json:"stats_app_version,omitempty"`
	StatsDeviceParams      *string            `protobuf:"bytes,25,opt,name=stats_device_params" json:"stats_device_params,omitempty"`
	StatsTransmittedBytes  *uint32            `protobuf:"varint,26,opt,name=stats_transmitted_bytes" json:"stats_transmitted_bytes,omitempty"`
	StatsReceivedBytes     *uint32            `protobuf:"varint,27,opt,name=stats_received_bytes" json:"stats_received_bytes,omitempty"`
	StatsOneshots          *uint32            `protobuf:"varint,28,opt,name=stats_oneshots" json:"stats_oneshots,omitempty"`
	StatsCommsResets       *uint32            `protobuf:"varint,29,opt,name=stats_comms_resets" json:"stats_comms_resets,omitempty"`
	PmsPm01_0              *uint32            `protobuf:"varint,30,opt,name=pms_pm01_0" json:"pms_pm01_0,omitempty"`
	PmsPm02_5              *uint32            `protobuf:"varint,31,opt,name=pms_pm02_5" json:"pms_pm02_5,omitempty"`
	PmsPm10_0              *uint32            `protobuf:"varint,32,opt,name=pms_pm10_0" json:"pms_pm10_0,omitempty"`
	PmsC00_30              *uint32            `protobuf:"varint,33,opt,name=pms_c00_30" json:"pms_c00_30,omitempty"`
	PmsC00_50              *uint32            `protobuf:"varint,34,opt,name=pms_c00_50" json:"pms_c00_50,omitempty"`
	PmsC01_00              *uint32            `protobuf:"varint,35,opt,name=pms_c01_00" json:"pms_c01_00,omitempty"`
	PmsC02_50              *uint32            `protobuf:"varint,36,opt,name=pms_c02_50" json:"pms_c02_50,omitempty"`
	PmsC05_00              *uint32            `protobuf:"varint,37,opt,name=pms_c05_00" json:"pms_c05_00,omitempty"`
	PmsC10_00              *uint32            `protobuf:"varint,38,opt,name=pms_c10_00" json:"pms_c10_00,omitempty"`
	PmsCsecs               *uint32            `protobuf:"varint,39,opt,name=pms_csecs" json:"pms_csecs,omitempty"`
	OpcPm01_0              *float32           `protobuf:"fixed32,40,opt,name=opc_pm01_0" json:"opc_pm01_0,omitempty"`
	OpcPm02_5              *float32           `protobuf:"fixed32,41,opt,name=opc_pm02_5" json:"opc_pm02_5,omitempty"`
	OpcPm10_0              *float32           `protobuf:"fixed32,42,opt,name=opc_pm10_0" json:"opc_pm10_0,omitempty"`
	OpcC00_38              *uint32            `protobuf:"varint,43,opt,name=opc_c00_38" json:"opc_c00_38,omitempty"`
	OpcC00_54              *uint32            `protobuf:"varint,44,opt,name=opc_c00_54" json:"opc_c00_54,omitempty"`
	OpcC01_00              *uint32            `protobuf:"varint,45,opt,name=opc_c01_00" json:"opc_c01_00,omitempty"`
	OpcC02_10              *uint32            `protobuf:"varint,46,opt,name=opc_c02_10" json:"opc_c02_10,omitempty"`
	OpcC05_00              *uint32            `protobuf:"varint,47,opt,name=opc_c05_00" json:"opc_c05_00,omitempty"`
	OpcC10_00              *uint32            `protobuf:"varint,48,opt,name=opc_c10_00" json:"opc_c10_00,omitempty"`
	OpcCsecs               *uint32            `protobuf:"varint,49,opt,name=opc_csecs" json:"opc_csecs,omitempty"`
	EnvPressure            *float32           `protobuf:"fixed32,50,opt,name=env_pressure" json:"env_pressure,omitempty"`
	StatsCommsPowerFails   *uint32            `protobuf:"varint,51,opt,name=stats_comms_power_fails" json:"stats_comms_power_fails,omitempty"`
	BatCurrent             *float32           `protobuf:"fixed32,52,opt,name=bat_current" json:"bat_current,omitempty"`
	StatsIccid             *string            `protobuf:"bytes,53,opt,name=stats_iccid" json:"stats_iccid,omitempty"`
	StatsMotiondrops       *uint32            `protobuf:"varint,54,opt,name=stats_motiondrops" json:"stats_motiondrops,omitempty"`
	StatsDfu               *string            `protobuf:"bytes,55,opt,name=stats_dfu" json:"stats_dfu,omitempty"`
	CapturedAtDate         *uint32            `protobuf:"varint,56,opt,name=captured_at_date" json:"captured_at_date,omitempty"`
	CapturedAtTime         *uint32            `protobuf:"varint,57,opt,name=captured_at_time" json:"captured_at_time,omitempty"`
	CapturedAtOffset       *uint32            `protobuf:"varint,58,opt,name=captured_at_offset" json:"captured_at_offset,omitempty"`
	StatsOneshotSeconds    *uint32            `protobuf:"varint,59,opt,name=stats_oneshot_seconds" json:"stats_oneshot_seconds,omitempty"`
	Stamp                  *uint32            `protobuf:"varint,60,opt,name=stamp" json:"stamp,omitempty"`
	StampVersion           *uint32            `protobuf:"varint,61,opt,name=stamp_version" json:"stamp_version,omitempty"`
	StatsCpsi              *string            `protobuf:"bytes,62,opt,name=stats_cpsi" json:"stats_cpsi,omitempty"`
	StatsUptimeDays        *uint32            `protobuf:"varint,63,opt,name=stats_uptime_days" json:"stats_uptime_days,omitempty"`
	StatsDeviceLabel       *string            `protobuf:"bytes,64,opt,name=stats_device_label" json:"stats_device_label,omitempty"`
	StatsGpsParams         *string            `protobuf:"bytes,65,opt,name=stats_gps_params" json:"stats_gps_params,omitempty"`
	StatsServiceParams     *string            `protobuf:"bytes,66,opt,name=stats_service_params" json:"stats_service_params,omitempty"`
	StatsTtnParams         *string            `protobuf:"bytes,67,opt,name=stats_ttn_params" json:"stats_ttn_params,omitempty"`
	StatsSensorParams      *string            `protobuf:"bytes,68,opt,name=stats_sensor_params" json:"stats_sensor_params,omitempty"`
	Lnd_7318C              *uint32            `protobuf:"varint,69,opt,name=lnd_7318c" json:"lnd_7318c,omitempty"`
	StatsBattery           *string            `protobuf:"bytes,70,opt,name=stats_battery" json:"stats_battery,omitempty"`
	StatsModuleFona        *string            `protobuf:"bytes,71,opt,name=stats_module_fona" json:"stats_module_fona,omitempty"`
	StatsModuleLora        *string            `protobuf:"bytes,72,opt,name=stats_module_lora" json:"stats_module_lora,omitempty"`
	Motion                 *bool              `protobuf:"varint,73,opt,name=motion" json:"motion,omitempty"`
	Test                   *bool              `protobuf:"varint,74,opt,name=test" json:"test,omitempty"`
	EncTemp                *float32           `protobuf:"fixed32,75,opt,name=enc_temp" json:"enc_temp,omitempty"`
	EncHumid               *float32           `protobuf:"fixed32,76,opt,name=enc_humid" json:"enc_humid,omitempty"`
	EncPressure            *float32           `protobuf:"fixed32,77,opt,name=enc_pressure" json:"enc_pressure,omitempty"`
	ErrorsOpc              *uint32            `protobuf:"varint,78,opt,name=errors_opc" json:"errors_opc,omitempty"`
	ErrorsPms              *uint32            `protobuf:"varint,79,opt,name=errors_pms" json:"errors_pms,omitempty"`
	ErrorsBme0             *uint32            `protobuf:"varint,80,opt,name=errors_bme0" json:"errors_bme0,omitempty"`
	ErrorsBme1             *uint32            `protobuf:"varint,81,opt,name=errors_bme1" json:"errors_bme1,omitempty"`
	ErrorsLora             *uint32            `protobuf:"varint,82,opt,name=errors_lora" json:"errors_lora,omitempty"`
	ErrorsFona             *uint32            `protobuf:"varint,83,opt,name=errors_fona" json:"errors_fona,omitempty"`
	ErrorsGeiger           *uint32            `protobuf:"varint,84,opt,name=errors_geiger" json:"errors_geiger,omitempty"`
	ErrorsMax01            *uint32            `protobuf:"varint,85,opt,name=errors_max01" json:"errors_max01,omitempty"`
	ErrorsUgps             *uint32            `protobuf:"varint,86,opt,name=errors_ugps" json:"errors_ugps,omitempty"`
	ErrorsTwi              *uint32            `protobuf:"varint,87,opt,name=errors_twi" json:"errors_twi,omitempty"`
	ErrorsTwiInfo          *string            `protobuf:"bytes,88,opt,name=errors_twi_info" json:"errors_twi_info,omitempty"`
	ErrorsLis              *uint32            `protobuf:"varint,89,opt,name=errors_lis" json:"errors_lis,omitempty"`
	ErrorsSpi              *uint32            `protobuf:"varint,90,opt,name=errors_spi" json:"errors_spi,omitempty"`
	ErrorsConnectLora      *uint32            `protobuf:"varint,91,opt,name=errors_connect_lora" json:"errors_connect_lora,omitempty"`
	ErrorsConnectFona      *uint32            `protobuf:"varint,92,opt,name=errors_connect_fona" json:"errors_connect_fona,omitempty"`
	ErrorsConnectWireless  *uint32            `protobuf:"varint,93,opt,name=errors_connect_wireless" json:"errors_connect_wireless,omitempty"`
	ErrorsConnectData      *uint32            `protobuf:"varint,94,opt,name=errors_connect_data" json:"errors_connect_data,omitempty"`
	ErrorsConnectService   *uint32            `protobuf:"varint,95,opt,name=errors_connect_service" json:"errors_connect_service,omitempty"`
	XXX_unrecognized       []byte             `json:"-"`
}

func (m *Telecast) Reset()                    { *m = Telecast{} }
func (m *Telecast) String() string            { return proto.CompactTextString(m) }
func (*Telecast) ProtoMessage()               {}
func (*Telecast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Telecast) GetDeviceType() TelecastDeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Telecast_UNKNOWN_DEVICE_TYPE
}

func (m *Telecast) GetDEPRECATED2017FEBDeviceIDString() string {
	if m != nil && m.DEPRECATED2017FEBDeviceIDString != nil {
		return *m.DEPRECATED2017FEBDeviceIDString
	}
	return ""
}

func (m *Telecast) GetDeviceId() uint32 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

func (m *Telecast) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Telecast) GetCapturedAt() string {
	if m != nil && m.CapturedAt != nil {
		return *m.CapturedAt
	}
	return ""
}

func (m *Telecast) GetReplyType() TelecastReplyType {
	if m != nil && m.ReplyType != nil {
		return *m.ReplyType
	}
	return Telecast_NO_REPLY
}

func (m *Telecast) GetDEPRECATED2017FEBValue() uint32 {
	if m != nil && m.DEPRECATED2017FEBValue != nil {
		return *m.DEPRECATED2017FEBValue
	}
	return 0
}

func (m *Telecast) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Telecast) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Telecast) GetAltitude() int32 {
	if m != nil && m.Altitude != nil {
		return *m.Altitude
	}
	return 0
}

func (m *Telecast) GetBatVoltage() float32 {
	if m != nil && m.BatVoltage != nil {
		return *m.BatVoltage
	}
	return 0
}

func (m *Telecast) GetBatSoc() float32 {
	if m != nil && m.BatSoc != nil {
		return *m.BatSoc
	}
	return 0
}

func (m *Telecast) GetWirelessSnr() float32 {
	if m != nil && m.WirelessSnr != nil {
		return *m.WirelessSnr
	}
	return 0
}

func (m *Telecast) GetEnvTemp() float32 {
	if m != nil && m.EnvTemp != nil {
		return *m.EnvTemp
	}
	return 0
}

func (m *Telecast) GetEnvHumid() float32 {
	if m != nil && m.EnvHumid != nil {
		return *m.EnvHumid
	}
	return 0
}

func (m *Telecast) GetRelayDevice1() uint32 {
	if m != nil && m.RelayDevice1 != nil {
		return *m.RelayDevice1
	}
	return 0
}

func (m *Telecast) GetRelayDevice2() uint32 {
	if m != nil && m.RelayDevice2 != nil {
		return *m.RelayDevice2
	}
	return 0
}

func (m *Telecast) GetRelayDevice3() uint32 {
	if m != nil && m.RelayDevice3 != nil {
		return *m.RelayDevice3
	}
	return 0
}

func (m *Telecast) GetRelayDevice4() uint32 {
	if m != nil && m.RelayDevice4 != nil {
		return *m.RelayDevice4
	}
	return 0
}

func (m *Telecast) GetRelayDevice5() uint32 {
	if m != nil && m.RelayDevice5 != nil {
		return *m.RelayDevice5
	}
	return 0
}

func (m *Telecast) GetLnd_7318U() uint32 {
	if m != nil && m.Lnd_7318U != nil {
		return *m.Lnd_7318U
	}
	return 0
}

func (m *Telecast) GetLnd_7128Ec() uint32 {
	if m != nil && m.Lnd_7128Ec != nil {
		return *m.Lnd_7128Ec
	}
	return 0
}

func (m *Telecast) GetStatsUptimeMinutes() uint32 {
	if m != nil && m.StatsUptimeMinutes != nil {
		return *m.StatsUptimeMinutes
	}
	return 0
}

func (m *Telecast) GetStatsAppVersion() string {
	if m != nil && m.StatsAppVersion != nil {
		return *m.StatsAppVersion
	}
	return ""
}

func (m *Telecast) GetStatsDeviceParams() string {
	if m != nil && m.StatsDeviceParams != nil {
		return *m.StatsDeviceParams
	}
	return ""
}

func (m *Telecast) GetStatsTransmittedBytes() uint32 {
	if m != nil && m.StatsTransmittedBytes != nil {
		return *m.StatsTransmittedBytes
	}
	return 0
}

func (m *Telecast) GetStatsReceivedBytes() uint32 {
	if m != nil && m.StatsReceivedBytes != nil {
		return *m.StatsReceivedBytes
	}
	return 0
}

func (m *Telecast) GetStatsOneshots() uint32 {
	if m != nil && m.StatsOneshots != nil {
		return *m.StatsOneshots
	}
	return 0
}

func (m *Telecast) GetStatsCommsResets() uint32 {
	if m != nil && m.StatsCommsResets != nil {
		return *m.StatsCommsResets
	}
	return 0
}

func (m *Telecast) GetPmsPm01_0() uint32 {
	if m != nil && m.PmsPm01_0 != nil {
		return *m.PmsPm01_0
	}
	return 0
}

func (m *Telecast) GetPmsPm02_5() uint32 {
	if m != nil && m.PmsPm02_5 != nil {
		return *m.PmsPm02_5
	}
	return 0
}

func (m *Telecast) GetPmsPm10_0() uint32 {
	if m != nil && m.PmsPm10_0 != nil {
		return *m.PmsPm10_0
	}
	return 0
}

func (m *Telecast) GetPmsC00_30() uint32 {
	if m != nil && m.PmsC00_30 != nil {
		return *m.PmsC00_30
	}
	return 0
}

func (m *Telecast) GetPmsC00_50() uint32 {
	if m != nil && m.PmsC00_50 != nil {
		return *m.PmsC00_50
	}
	return 0
}

func (m *Telecast) GetPmsC01_00() uint32 {
	if m != nil && m.PmsC01_00 != nil {
		return *m.PmsC01_00
	}
	return 0
}

func (m *Telecast) GetPmsC02_50() uint32 {
	if m != nil && m.PmsC02_50 != nil {
		return *m.PmsC02_50
	}
	return 0
}

func (m *Telecast) GetPmsC05_00() uint32 {
	if m != nil && m.PmsC05_00 != nil {
		return *m.PmsC05_00
	}
	return 0
}

func (m *Telecast) GetPmsC10_00() uint32 {
	if m != nil && m.PmsC10_00 != nil {
		return *m.PmsC10_00
	}
	return 0
}

func (m *Telecast) GetPmsCsecs() uint32 {
	if m != nil && m.PmsCsecs != nil {
		return *m.PmsCsecs
	}
	return 0
}

func (m *Telecast) GetOpcPm01_0() float32 {
	if m != nil && m.OpcPm01_0 != nil {
		return *m.OpcPm01_0
	}
	return 0
}

func (m *Telecast) GetOpcPm02_5() float32 {
	if m != nil && m.OpcPm02_5 != nil {
		return *m.OpcPm02_5
	}
	return 0
}

func (m *Telecast) GetOpcPm10_0() float32 {
	if m != nil && m.OpcPm10_0 != nil {
		return *m.OpcPm10_0
	}
	return 0
}

func (m *Telecast) GetOpcC00_38() uint32 {
	if m != nil && m.OpcC00_38 != nil {
		return *m.OpcC00_38
	}
	return 0
}

func (m *Telecast) GetOpcC00_54() uint32 {
	if m != nil && m.OpcC00_54 != nil {
		return *m.OpcC00_54
	}
	return 0
}

func (m *Telecast) GetOpcC01_00() uint32 {
	if m != nil && m.OpcC01_00 != nil {
		return *m.OpcC01_00
	}
	return 0
}

func (m *Telecast) GetOpcC02_10() uint32 {
	if m != nil && m.OpcC02_10 != nil {
		return *m.OpcC02_10
	}
	return 0
}

func (m *Telecast) GetOpcC05_00() uint32 {
	if m != nil && m.OpcC05_00 != nil {
		return *m.OpcC05_00
	}
	return 0
}

func (m *Telecast) GetOpcC10_00() uint32 {
	if m != nil && m.OpcC10_00 != nil {
		return *m.OpcC10_00
	}
	return 0
}

func (m *Telecast) GetOpcCsecs() uint32 {
	if m != nil && m.OpcCsecs != nil {
		return *m.OpcCsecs
	}
	return 0
}

func (m *Telecast) GetEnvPressure() float32 {
	if m != nil && m.EnvPressure != nil {
		return *m.EnvPressure
	}
	return 0
}

func (m *Telecast) GetStatsCommsPowerFails() uint32 {
	if m != nil && m.StatsCommsPowerFails != nil {
		return *m.StatsCommsPowerFails
	}
	return 0
}

func (m *Telecast) GetBatCurrent() float32 {
	if m != nil && m.BatCurrent != nil {
		return *m.BatCurrent
	}
	return 0
}

func (m *Telecast) GetStatsIccid() string {
	if m != nil && m.StatsIccid != nil {
		return *m.StatsIccid
	}
	return ""
}

func (m *Telecast) GetStatsMotiondrops() uint32 {
	if m != nil && m.StatsMotiondrops != nil {
		return *m.StatsMotiondrops
	}
	return 0
}

func (m *Telecast) GetStatsDfu() string {
	if m != nil && m.StatsDfu != nil {
		return *m.StatsDfu
	}
	return ""
}

func (m *Telecast) GetCapturedAtDate() uint32 {
	if m != nil && m.CapturedAtDate != nil {
		return *m.CapturedAtDate
	}
	return 0
}

func (m *Telecast) GetCapturedAtTime() uint32 {
	if m != nil && m.CapturedAtTime != nil {
		return *m.CapturedAtTime
	}
	return 0
}

func (m *Telecast) GetCapturedAtOffset() uint32 {
	if m != nil && m.CapturedAtOffset != nil {
		return *m.CapturedAtOffset
	}
	return 0
}

func (m *Telecast) GetStatsOneshotSeconds() uint32 {
	if m != nil && m.StatsOneshotSeconds != nil {
		return *m.StatsOneshotSeconds
	}
	return 0
}

func (m *Telecast) GetStamp() uint32 {
	if m != nil && m.Stamp != nil {
		return *m.Stamp
	}
	return 0
}

func (m *Telecast) GetStampVersion() uint32 {
	if m != nil && m.StampVersion != nil {
		return *m.StampVersion
	}
	return 0
}

func (m *Telecast) GetStatsCpsi() string {
	if m != nil && m.StatsCpsi != nil {
		return *m.StatsCpsi
	}
	return ""
}

func (m *Telecast) GetStatsUptimeDays() uint32 {
	if m != nil && m.StatsUptimeDays != nil {
		return *m.StatsUptimeDays
	}
	return 0
}

func (m *Telecast) GetStatsDeviceLabel() string {
	if m != nil && m.StatsDeviceLabel != nil {
		return *m.StatsDeviceLabel
	}
	return ""
}

func (m *Telecast) GetStatsGpsParams() string {
	if m != nil && m.StatsGpsParams != nil {
		return *m.StatsGpsParams
	}
	return ""
}

func (m *Telecast) GetStatsServiceParams() string {
	if m != nil && m.StatsServiceParams != nil {
		return *m.StatsServiceParams
	}
	return ""
}

func (m *Telecast) GetStatsTtnParams() string {
	if m != nil && m.StatsTtnParams != nil {
		return *m.StatsTtnParams
	}
	return ""
}

func (m *Telecast) GetStatsSensorParams() string {
	if m != nil && m.StatsSensorParams != nil {
		return *m.StatsSensorParams
	}
	return ""
}

func (m *Telecast) GetLnd_7318C() uint32 {
	if m != nil && m.Lnd_7318C != nil {
		return *m.Lnd_7318C
	}
	return 0
}

func (m *Telecast) GetStatsBattery() string {
	if m != nil && m.StatsBattery != nil {
		return *m.StatsBattery
	}
	return ""
}

func (m *Telecast) GetStatsModuleFona() string {
	if m != nil && m.StatsModuleFona != nil {
		return *m.StatsModuleFona
	}
	return ""
}

func (m *Telecast) GetStatsModuleLora() string {
	if m != nil && m.StatsModuleLora != nil {
		return *m.StatsModuleLora
	}
	return ""
}

func (m *Telecast) GetMotion() bool {
	if m != nil && m.Motion != nil {
		return *m.Motion
	}
	return false
}

func (m *Telecast) GetTest() bool {
	if m != nil && m.Test != nil {
		return *m.Test
	}
	return false
}

func (m *Telecast) GetEncTemp() float32 {
	if m != nil && m.EncTemp != nil {
		return *m.EncTemp
	}
	return 0
}

func (m *Telecast) GetEncHumid() float32 {
	if m != nil && m.EncHumid != nil {
		return *m.EncHumid
	}
	return 0
}

func (m *Telecast) GetEncPressure() float32 {
	if m != nil && m.EncPressure != nil {
		return *m.EncPressure
	}
	return 0
}

func (m *Telecast) GetErrorsOpc() uint32 {
	if m != nil && m.ErrorsOpc != nil {
		return *m.ErrorsOpc
	}
	return 0
}

func (m *Telecast) GetErrorsPms() uint32 {
	if m != nil && m.ErrorsPms != nil {
		return *m.ErrorsPms
	}
	return 0
}

func (m *Telecast) GetErrorsBme0() uint32 {
	if m != nil && m.ErrorsBme0 != nil {
		return *m.ErrorsBme0
	}
	return 0
}

func (m *Telecast) GetErrorsBme1() uint32 {
	if m != nil && m.ErrorsBme1 != nil {
		return *m.ErrorsBme1
	}
	return 0
}

func (m *Telecast) GetErrorsLora() uint32 {
	if m != nil && m.ErrorsLora != nil {
		return *m.ErrorsLora
	}
	return 0
}

func (m *Telecast) GetErrorsFona() uint32 {
	if m != nil && m.ErrorsFona != nil {
		return *m.ErrorsFona
	}
	return 0
}

func (m *Telecast) GetErrorsGeiger() uint32 {
	if m != nil && m.ErrorsGeiger != nil {
		return *m.ErrorsGeiger
	}
	return 0
}

func (m *Telecast) GetErrorsMax01() uint32 {
	if m != nil && m.ErrorsMax01 != nil {
		return *m.ErrorsMax01
	}
	return 0
}

func (m *Telecast) GetErrorsUgps() uint32 {
	if m != nil && m.ErrorsUgps != nil {
		return *m.ErrorsUgps
	}
	return 0
}

func (m *Telecast) GetErrorsTwi() uint32 {
	if m != nil && m.ErrorsTwi != nil {
		return *m.ErrorsTwi
	}
	return 0
}

func (m *Telecast) GetErrorsTwiInfo() string {
	if m != nil && m.ErrorsTwiInfo != nil {
		return *m.ErrorsTwiInfo
	}
	return ""
}

func (m *Telecast) GetErrorsLis() uint32 {
	if m != nil && m.ErrorsLis != nil {
		return *m.ErrorsLis
	}
	return 0
}

func (m *Telecast) GetErrorsSpi() uint32 {
	if m != nil && m.ErrorsSpi != nil {
		return *m.ErrorsSpi
	}
	return 0
}

func (m *Telecast) GetErrorsConnectLora() uint32 {
	if m != nil && m.ErrorsConnectLora != nil {
		return *m.ErrorsConnectLora
	}
	return 0
}

func (m *Telecast) GetErrorsConnectFona() uint32 {
	if m != nil && m.ErrorsConnectFona != nil {
		return *m.ErrorsConnectFona
	}
	return 0
}

func (m *Telecast) GetErrorsConnectWireless() uint32 {
	if m != nil && m.ErrorsConnectWireless != nil {
		return *m.ErrorsConnectWireless
	}
	return 0
}

func (m *Telecast) GetErrorsConnectData() uint32 {
	if m != nil && m.ErrorsConnectData != nil {
		return *m.ErrorsConnectData
	}
	return 0
}

func (m *Telecast) GetErrorsConnectService() uint32 {
	if m != nil && m.ErrorsConnectService != nil {
		return *m.ErrorsConnectService
	}
	return 0
}

func init() {
	proto.RegisterType((*Telecast)(nil), "ttproto.Telecast")
	proto.RegisterEnum("ttproto.TelecastDeviceType", TelecastDeviceType_name, TelecastDeviceType_value)
	proto.RegisterEnum("ttproto.TelecastReplyType", TelecastReplyType_name, TelecastReplyType_value)
}

var fileDescriptor0 = []byte{
	// 1118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x96, 0xfb, 0x57, 0xdb, 0x36,
	0x14, 0xc7, 0x47, 0x5b, 0x20, 0x11, 0x8f, 0x06, 0xf3, 0xba, 0x2d, 0xb4, 0x74, 0xec, 0xd1, 0x6e,
	0xeb, 0xa8, 0x13, 0x60, 0xb0, 0xf7, 0x02, 0x71, 0x19, 0x2b, 0x4b, 0x32, 0x70, 0x61, 0xec, 0xa5,
	0x63, 0x1c, 0x25, 0xf5, 0x39, 0x7e, 0x1d, 0x49, 0x09, 0xcb, 0x9f, 0xbb, 0xff, 0x64, 0xf2, 0xb5,
	0x15, 0x62, 0x43, 0x7f, 0x4b, 0x3e, 0xdf, 0x2b, 0xe9, 0x7e, 0x75, 0xef, 0x55, 0x42, 0x4a, 0x52,
	0x6e, 0xc5, 0x3c, 0x92, 0x91, 0x31, 0x2d, 0x25, 0x7e, 0xd8, 0xfc, 0xcf, 0x20, 0x25, 0x9b, 0xf9,
	0xcc, 0x75, 0x84, 0x34, 0xaa, 0x64, 0xa6, 0xc3, 0x06, 0x9e, 0xcb, 0xa8, 0x1c, 0xc6, 0x0c, 0x26,
	0x9e, 0x4d, 0xbc, 0x98, 0xaf, 0xad, 0x6f, 0x65, 0xb1, 0x5b, 0x3a, 0x6e, 0x2b, 0x0d, 0xb2, 0x55,
	0x8c, 0xf1, 0x9c, 0x6c, 0x34, 0xac, 0xf6, 0xa9, 0x75, 0x58, 0xb7, 0xad, 0x46, 0xcd, 0xac, 0xee,
	0xbd, 0xb6, 0x0e, 0x1a, 0x28, 0x1f, 0x37, 0xce, 0x24, 0xf7, 0xc2, 0x1e, 0xdc, 0x53, 0xdb, 0x94,
	0x8d, 0x05, 0x52, 0xce, 0xf6, 0xf6, 0x3a, 0x70, 0x5f, 0xa1, 0x39, 0xe3, 0x21, 0x99, 0x0e, 0x98,
	0x10, 0x4e, 0x8f, 0xc1, 0x03, 0x8c, 0x59, 0x24, 0x33, 0xae, 0x13, 0xcb, 0x3e, 0x67, 0x1d, 0xea,
	0x48, 0x98, 0x44, 0xf8, 0x8a, 0x10, 0xce, 0x62, 0x7f, 0x98, 0xe6, 0x34, 0x85, 0x39, 0xad, 0xdd,
	0xce, 0x09, 0x63, 0x30, 0xa5, 0xa7, 0x64, 0xe5, 0x56, 0x4a, 0xe7, 0x8e, 0xdf, 0x67, 0x30, 0x8d,
	0xc7, 0x56, 0x48, 0xc9, 0x77, 0xa4, 0x27, 0xfb, 0x1d, 0x06, 0x25, 0x45, 0xee, 0x25, 0xb9, 0xf9,
	0x51, 0xd8, 0x4b, 0x51, 0x19, 0x91, 0x0a, 0x72, 0xfc, 0x2c, 0x88, 0x28, 0x32, 0x99, 0x24, 0x77,
	0xe5, 0x48, 0x3a, 0x88, 0x7c, 0x99, 0x64, 0x3c, 0x83, 0x61, 0xca, 0x42, 0x02, 0x45, 0xe4, 0xc2,
	0x2c, 0x82, 0x25, 0x32, 0x7b, 0xed, 0x71, 0x95, 0x94, 0x10, 0x54, 0x84, 0x1c, 0xe6, 0xf4, 0x6e,
	0x2c, 0x1c, 0x50, 0xc9, 0x82, 0x18, 0xe6, 0xf5, 0x91, 0x09, 0x79, 0xd7, 0x0f, 0xd4, 0x75, 0x3c,
	0x44, 0xb4, 0x4c, 0xe6, 0xd4, 0x42, 0x67, 0x48, 0xd3, 0x7b, 0xaa, 0x42, 0x05, 0xd3, 0x2d, 0xe0,
	0x1a, 0x2c, 0xdc, 0x85, 0xb7, 0xc1, 0xb8, 0x0b, 0xef, 0xc0, 0xe2, 0x5d, 0x78, 0x17, 0x96, 0x10,
	0x27, 0xc6, 0xc3, 0x0e, 0xdd, 0xdb, 0xae, 0xee, 0xf7, 0x61, 0x19, 0x91, 0x41, 0x08, 0xa2, 0x6a,
	0x6d, 0x9f, 0xb9, 0xb0, 0x82, 0x6c, 0x9d, 0x2c, 0x09, 0xe9, 0x48, 0x41, 0xfb, 0xb1, 0xf4, 0x02,
	0x46, 0x03, 0x2f, 0xec, 0x4b, 0x26, 0x60, 0x15, 0xd5, 0x47, 0x64, 0x21, 0x55, 0x9d, 0x38, 0xa6,
	0x03, 0xc6, 0x85, 0x17, 0x85, 0x00, 0x58, 0xbb, 0x35, 0xb2, 0x98, 0x4a, 0x59, 0xe9, 0x63, 0x87,
	0x3b, 0x81, 0x80, 0x47, 0x28, 0x6e, 0x90, 0xd5, 0x54, 0x94, 0xdc, 0x09, 0x45, 0xe0, 0x49, 0xa9,
	0xca, 0x7e, 0x35, 0x4c, 0x36, 0x7e, 0x9c, 0x3f, 0x96, 0x33, 0x97, 0x79, 0x83, 0x91, 0xba, 0x86,
	0xea, 0x0a, 0x99, 0x4f, 0xd5, 0x28, 0x64, 0xe2, 0x5d, 0x24, 0x05, 0xac, 0x23, 0x7f, 0x4c, 0x8c,
	0x94, 0xbb, 0x51, 0x10, 0x24, 0x6b, 0x05, 0x53, 0xda, 0x13, 0x6d, 0x2e, 0x56, 0x2c, 0x0e, 0xcc,
	0x2a, 0x35, 0xe1, 0x69, 0x81, 0xd5, 0xe8, 0x2e, 0x6c, 0xe4, 0x59, 0xd5, 0x54, 0x71, 0xcf, 0xc6,
	0x99, 0x6b, 0x9a, 0x74, 0xdb, 0x84, 0x0f, 0x8b, 0x6c, 0xd7, 0x84, 0xcd, 0x3c, 0x53, 0x47, 0x98,
	0xf0, 0x51, 0x9e, 0xd5, 0x92, 0xb8, 0x8f, 0xf3, 0x6c, 0x37, 0x89, 0xfb, 0x24, 0xc7, 0x92, 0x63,
	0x4d, 0xf8, 0x54, 0xd7, 0x08, 0x99, 0x60, 0xae, 0x80, 0xe7, 0x3a, 0x2c, 0x8a, 0x5d, 0x6d, 0xe3,
	0x05, 0x76, 0xcf, 0x0d, 0x4b, 0x6c, 0x7c, 0x96, 0x67, 0x68, 0xe3, 0xf3, 0x71, 0x86, 0x36, 0xf6,
	0xe1, 0x8b, 0xf1, 0xfd, 0xd0, 0xc6, 0x0e, 0xbc, 0xcc, 0x33, 0xb4, 0xf1, 0x65, 0x9e, 0xd5, 0x68,
	0xd5, 0x84, 0xad, 0x3c, 0x43, 0x1b, 0xaf, 0x72, 0x2c, 0xb5, 0x61, 0x6a, 0x1b, 0xc8, 0xd0, 0x46,
	0x15, 0x91, 0x9a, 0x95, 0x64, 0x06, 0x62, 0x55, 0x22, 0xa1, 0x66, 0x1e, 0x6a, 0x98, 0xe0, 0xa8,
	0x2d, 0xd2, 0xfa, 0xc5, 0xd1, 0x35, 0xe3, 0xb4, 0xeb, 0x78, 0xbe, 0x80, 0x6d, 0x5c, 0x96, 0x0d,
	0xa2, 0xdb, 0xe7, 0x9c, 0x85, 0x12, 0x76, 0x70, 0x95, 0x82, 0xe9, 0x2a, 0xcf, 0x75, 0xd5, 0x44,
	0xed, 0x62, 0x87, 0x8d, 0x3a, 0x33, 0x88, 0xa4, 0x6a, 0xca, 0x0e, 0x8f, 0x62, 0x01, 0x5f, 0xe9,
	0x74, 0xb2, 0xce, 0xec, 0xf6, 0x61, 0x0f, 0xa3, 0x81, 0x54, 0xc6, 0x5e, 0x1f, 0xda, 0x71, 0x24,
	0x83, 0x7d, 0x0c, 0x2e, 0x28, 0xc9, 0x0c, 0xc0, 0xd7, 0xba, 0xd9, 0xc6, 0x95, 0xa8, 0xdb, 0x55,
	0xdd, 0x06, 0xdf, 0xa0, 0xf6, 0x84, 0x2c, 0xe7, 0x1a, 0x94, 0x2a, 0xeb, 0x2a, 0x09, 0x01, 0xdf,
	0xa2, 0x3c, 0x47, 0x26, 0x95, 0xac, 0x1e, 0x84, 0xef, 0xf4, 0x84, 0xe2, 0xd7, 0xd1, 0x04, 0x7d,
	0xaf, 0xaf, 0x32, 0xbb, 0x8d, 0x58, 0x78, 0xf0, 0x43, 0xde, 0x56, 0x36, 0x8e, 0x1d, 0x67, 0x28,
	0xe0, 0xc7, 0x7c, 0xf3, 0x67, 0x03, 0xe7, 0x3b, 0x57, 0xcc, 0x87, 0x9f, 0xb4, 0xbf, 0x54, 0xeb,
	0xc5, 0x42, 0x4f, 0x62, 0x1d, 0x95, 0xd1, 0xa0, 0x09, 0xc6, 0xc7, 0xe7, 0xf4, 0x20, 0xbf, 0x4e,
	0xca, 0x50, 0x2b, 0x87, 0xf9, 0xf1, 0x16, 0x2c, 0x14, 0x11, 0xd7, 0x62, 0x43, 0x3f, 0xf8, 0xfa,
	0x6d, 0x71, 0xc1, 0x1a, 0xf3, 0xa8, 0xe2, 0x55, 0xfd, 0x24, 0xe3, 0x43, 0x78, 0x5d, 0x2c, 0x53,
	0xa7, 0xef, 0x33, 0xda, 0x8d, 0x42, 0x07, 0x8e, 0xee, 0x94, 0xfc, 0x88, 0x3b, 0xf0, 0x33, 0x4a,
	0xf3, 0x64, 0x2a, 0x2d, 0x2b, 0x1c, 0xab, 0xef, 0x25, 0x63, 0x96, 0x3c, 0x50, 0x8f, 0x83, 0x84,
	0x5f, 0xf0, 0x1b, 0xbe, 0xb8, 0x6e, 0xfa, 0xe2, 0xbe, 0xb9, 0x79, 0x71, 0xdd, 0xec, 0xc5, 0x3d,
	0xd1, 0x8f, 0x75, 0x82, 0x46, 0x0d, 0xf8, 0xab, 0x9e, 0x10, 0xc6, 0x79, 0xc4, 0x55, 0xe1, 0x62,
	0x17, 0x9a, 0xba, 0x0c, 0x19, 0x53, 0xb3, 0x08, 0x2d, 0xdd, 0x87, 0x19, 0xbb, 0x0a, 0x98, 0x09,
	0xed, 0xdb, 0xb0, 0x0a, 0xbf, 0x15, 0x20, 0xe6, 0x7f, 0x5a, 0x80, 0xe8, 0xf7, 0x4c, 0xdf, 0x50,
	0x06, 0x7b, 0xcc, 0xeb, 0x31, 0x0e, 0xf6, 0x68, 0x52, 0x52, 0x1c, 0x38, 0xff, 0x9a, 0x55, 0x78,
	0x5b, 0xd8, 0xa1, 0xaf, 0x4a, 0x0a, 0xe7, 0x85, 0x4c, 0xe5, 0xb5, 0x07, 0x17, 0xc8, 0x56, 0xc9,
	0xc3, 0x1b, 0x46, 0xbd, 0xb0, 0x1b, 0xc1, 0xef, 0x78, 0x87, 0x37, 0xc1, 0xbe, 0x27, 0xe0, 0xb2,
	0xb0, 0x81, 0x88, 0x3d, 0xf8, 0x03, 0x99, 0x2a, 0x74, 0xc6, 0x54, 0x07, 0x87, 0xcc, 0x95, 0xa9,
	0x91, 0x3f, 0xdf, 0x23, 0xa2, 0xa1, 0xbf, 0x50, 0x54, 0xd3, 0x5c, 0x10, 0xf5, 0xcf, 0x23, 0xfc,
	0xfd, 0x9e, 0xd5, 0x6a, 0xf0, 0x1c, 0xf8, 0x07, 0x45, 0xf5, 0x53, 0x5e, 0x10, 0xb3, 0x0e, 0x05,
	0x9a, 0xe8, 0x9b, 0x03, 0x42, 0xc6, 0xfe, 0x8b, 0xac, 0x92, 0xc5, 0xb7, 0xcd, 0x37, 0xcd, 0xd6,
	0x45, 0x93, 0x36, 0xac, 0xf3, 0xe3, 0x43, 0x8b, 0xda, 0x97, 0x6d, 0xab, 0xf2, 0x81, 0x6a, 0x86,
	0xd9, 0x83, 0x23, 0xeb, 0xf8, 0xe8, 0xd8, 0xa2, 0xcd, 0x7a, 0xb3, 0x55, 0x99, 0x50, 0xc3, 0x57,
	0x3e, 0x6b, 0x9d, 0xd4, 0x4f, 0x0f, 0xeb, 0x67, 0x76, 0xe5, 0x9e, 0x51, 0x26, 0x93, 0xb6, 0x5d,
	0x6f, 0xb7, 0x2b, 0xf7, 0x95, 0xfb, 0x29, 0xdb, 0x6e, 0xb6, 0x1a, 0x56, 0xe5, 0x41, 0xfa, 0xf9,
	0x48, 0xfd, 0x8d, 0xa8, 0x4c, 0x1a, 0x33, 0x64, 0xda, 0xb6, 0xcf, 0xac, 0xd3, 0x73, 0xab, 0x32,
	0xb5, 0xf9, 0x92, 0x94, 0x6f, 0xfe, 0x6f, 0xcc, 0x92, 0x52, 0xb3, 0x45, 0x4f, 0xad, 0xf6, 0xc9,
	0xa5, 0x3a, 0x6b, 0x81, 0xcc, 0xe1, 0x47, 0x5a, 0x3f, 0x39, 0x69, 0x5d, 0x58, 0x8d, 0xca, 0xc4,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0xa7, 0xf4, 0x75, 0x77, 0x09, 0x00, 0x00,
}
