/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Sat Jun  4 15:16:22 2016. */

#include "teletype.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t teletype_Telecast_fields[10] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, teletype_Telecast, DeviceType, DeviceType, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, teletype_Telecast, DeviceID, DeviceType, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, teletype_Telecast, Message, DeviceID, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, teletype_Telecast, CapturedAt, Message, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, teletype_Telecast, Unit, CapturedAt, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, teletype_Telecast, Value, Unit, 0),
    PB_FIELD(  7, DOUBLE  , OPTIONAL, STATIC  , OTHER, teletype_Telecast, Latitude, Value, 0),
    PB_FIELD(  8, DOUBLE  , OPTIONAL, STATIC  , OTHER, teletype_Telecast, Longitude, Latitude, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, teletype_Telecast, Altitude, Longitude, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
